marttiphpbb_calendar_defaultview_controller:
    pattern: /calendar
    defaults: { _controller: marttiphpbb.calendar.controller:defaultview }
    requirements:
        _method: GET

marttiphpbb_calendar_yearview_controller:
    pattern: /calendar/{year}
    defaults: { _controller: marttiphpbb.calendar.controller:yearview }
    requirements:
        _method: GET
        year: ^(19|20)[0-9]{2}$

marttiphpbb_calendar_monthview_controller:
    pattern: /calendar/{year}/{month}
    defaults: { _controller: marttiphpbb.calendar.controller:monthview }
    requirements:
        _method: GET
        year: ^(19|20)[0-9]{2}$
        month: ^[1-9]|1[012]$

marttiphpbb_calendar_dayview_controller:
    pattern: /calendar/{year}/{month}/{day}
    defaults: { _controller: marttiphpbb.calendar.controller:dayview }
    requirements:
        _method: GET
        year: ^(19|20)[0-9]{2}$
        month: ^[1-9]|1[012]$
        day: ^[1-9]|[12][0-9]|3[01]$

marttiphpbb_calendar_continuousview_controller:
    pattern: /calendar/{year}/{month}/{day}/{length}/{precision}
    defaults: { _controller: marttiphpbb.calendar.controller:continuousview, precision: 1 }
    requirements:
        _method: GET
        year: ^(19|20)[0-9]{2}$
        month: ^[1-9]|1[012]$
        day: ^[1-9]|[12][0-9]|3[01]$
        length: ^[1-9]\d?|[1-4]\d\d$
        precision: ^\d+
