marttiphpbb_calendarinput_defaultview_controller:
    pattern: /calendarinput
    defaults: { _controller: marttiphpbb.calendarinput.controller:defaultview }
    requirements:
        _method: GET

marttiphpbb_calendarinput_yearview_controller:
    pattern: /calendarinput/{year}
    defaults: { _controller: marttiphpbb.calendarinput.controller:yearview }
    requirements:
        _method: GET
        year: ^(19|20)[0-9]{2}$

marttiphpbb_calendarinput_monthview_controller:
    pattern: /calendarinput/{year}/{month}
    defaults: { _controller: marttiphpbb.calendarinput.controller:monthview }
    requirements:
        _method: GET
        year: ^(19|20)[0-9]{2}$
        month: ^[1-9]|1[012]$

