services:
    marttiphpbb.calendarinput.main_listener:
        class: marttiphpbb\calendarinput\event\main_listener
        arguments:
            - '@controller.helper'
            - '%core.php_ext%'
            - '@template'
            - '@language'
            - '@marttiphpbb.calendarinput.render.links'
        tags:
            - { name: event.listener }

    marttiphpbb.calendarinput.tag_listener:
        class: marttiphpbb\calendarinput\event\tag_listener
        arguments:
            - '@template'
            - '@marttiphpbb.calendarinput.render.tag'
        tags:
            - { name: event.listener }

    marttiphpbb.calendarinput.posting_listener:
        class: marttiphpbb\calendarinput\event\posting_listener
        arguments:
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@marttiphpbb.calendarinput.render.include_assets'
            - '@marttiphpbb.calendarinput.render.input_settings'
            - '@marttiphpbb.calendarinput.render.posting'
        tags:
            - { name: event.listener }

    marttiphpbb.calendarinput.controller:
        class: marttiphpbb\calendarinput\controller\main
        arguments:
            - '@auth'
            - '@cache'
            - '@config'
            - '@dbal.conn'
            - '%core.php_ext%'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@controller.helper'
            - '%core.root_path%'
            - '@marttiphpbb.calendarinput.core.event_container'
            - '@marttiphpbb.calendarinput.moonphase_calculator'
            - '@marttiphpbb.calendarinput.timeformat'
            - '@marttiphpbb.calendarinput.render.render_settings'
            - '@marttiphpbb.calendarinput.render.pagination'

    marttiphpbb.calendarinput.core.event_container:
        class: marttiphpbb\calendarinput\core\event_container
        arguments:
            - '@auth'
            - '@config'
            - '@content.visibility'
            - '@dbal.conn'
            - '%tables.topics%'

    marttiphpbb.calendarinput.moonphase_calculator:
        class: marttiphpbb\calendarinput\util\moonphase_calculator

    marttiphpbb.calendarinput.timeformat:
        class: marttiphpbb\calendarinput\util\timeformat
        arguments:
            - '@user'

    marttiphpbb.calendarinput.render.links:
        class: marttiphpbb\calendarinput\render\links
        arguments:
            - '@config'
            - '@template'
            - '@language'

    marttiphpbb.calendarinput.render.include_assets:
        class: marttiphpbb\calendarinput\render\include_assets
        arguments:
            - '@config'
            - '@template'
            - '@language'
            - '%core.root_path%'

    marttiphpbb.calendarinput.render.render_settings:
        class: marttiphpbb\calendarinput\render\render_settings
        arguments:
            - '@config'
            - '@template'
            - '@language'

    marttiphpbb.calendarinput.render.pagination:
        class: marttiphpbb\calendarinput\render\pagination
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@language'

    marttiphpbb.calendarinput.render.input_settings:
        class: marttiphpbb\calendarinput\render\input_settings
        arguments:
            - '@config'
            - '@config_text'
            - '@template'
            - '@language'

    marttiphpbb.calendarinput.render.input_settings:
        class: marttiphpbb\calendarinput\render\input_settings
        arguments:
            - '@config'
            - '@template'
            - '@language'
            - '@marttiphpbb.calendarinput.render.input_settings'
            - '@marttiphpbb.calendarinput.render.include_assets'

    marttiphpbb.calendarinput.render.tag:
        class: marttiphpbb\calendarinput\render\tag
        arguments:
            - '@controller.helper'
            - '@marttiphpbb.calendarinput.dateformat'

    marttiphpbb.calendarinput.render.posting:
        class: marttiphpbb\calendarinput\render\posting
        arguments:
            - '@config'
            - '@template'
            - '@language'
            - '@marttiphpbb.calendarinput.render.input_settings'
            - '@marttiphpbb.calendarinput.render.include_assets'

    marttiphpbb.calendarinput.dateformat:
        class: marttiphpbb\calendarinput\util\dateformat
        arguments:
            - '@user'
            - '@language'
