services:
    marttiphpbb.calendar.main_listener:
        class: marttiphpbb\calendar\event\main_listener
        arguments:
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '%core.php_ext%'
            - '@template'
            - '@user'
            - '@marttiphpbb.calendar.render.links'
        tags:
            - { name: event.listener }

    marttiphpbb.calendar.suffix_listener:
        class: marttiphpbb\calendar\event\suffix_listener
        arguments:
            - '@config'
            - '@controller.helper'
            - '%core.php_ext%'
            - '@template'
            - '@marttiphpbb.calendar.dateformat'
        tags:
            - { name: event.listener }

    marttiphpbb.calendar.posting_listener:
        class: marttiphpbb\calendar\event\posting_listener
        arguments:
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '%core.php_ext%'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@marttiphpbb.calendar.render.include_assets'
            - '@marttiphpbb.calendar.render.input_settings'
        tags:
            - { name: event.listener }

    marttiphpbb.calendar.controller:
        class: marttiphpbb\calendar\controller\main
        arguments:
            - '@auth'
            - '@cache'
            - '@config'
            - '@dbal.conn'
            - '%core.php_ext%'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@controller.helper'
            - '%core.root_path%'
            - '@marttiphpbb.calendar.core.event_container'
            - '@marttiphpbb.calendar.moonphase_calculator'
            - '@marttiphpbb.calendar.timeformat'
            - '@marttiphpbb.calendar.render.render_settings'
            - '@marttiphpbb.calendar.render.pagination'

    marttiphpbb.calendar.core.event_container:
        class: marttiphpbb\calendar\core\event_container
        arguments:
            - '@auth'
            - '@config'
            - '@content.visibility'
            - '@dbal.conn'
            - '%tables.topics%'

    marttiphpbb.calendar.moonphase_calculator:
        class: marttiphpbb\calendar\util\moonphase_calculator

    marttiphpbb.calendar.timeformat:
        class: marttiphpbb\calendar\util\timeformat
        arguments:
            - '@user'

    marttiphpbb.calendar.render.links:
        class: marttiphpbb\calendar\render\links
        arguments:
            - '@config'
            - '@template'
            - '@language'

    marttiphpbb.calendar.render.include_assets:
        class: marttiphpbb\calendar\render\include_assets
        arguments:
            - '@config'
            - '@template'
            - '@language'
            - '%core.root_path%'

    marttiphpbb.calendar.render.render_settings:
        class: marttiphpbb\calendar\render\render_settings
        arguments:
            - '@config'
            - '@template'
            - '@language'

    marttiphpbb.calendar.render.pagination:
        class: marttiphpbb\calendar\render\pagination
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@language'

    marttiphpbb.calendar.render.input_settings:
        class: marttiphpbb\calendar\render\input_settings
        arguments:
            - '@config'
            - '@config_text'
            - '@template'
            - '@language'

    marttiphpbb.calendar.dateformat:
        class: marttiphpbb\calendar\util\dateformat
        arguments:
            - '@user'
            - '@language'
